image: cypress/base:12

stages:
  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

test:
  stage: test
  script:
    - npx cypress run
  artifacts:
    when: always
    paths:
      - cypress/reports
      - cypress/screenshots
    reports:
      junit:
        - cypress/reports/junit-report.xml
  dependencies: []
