name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      cypress:
        image: cypress/included:8.5.0  # Adjust Cypress Docker image version as needed
        ports:
          - 3000:3000  # Expose necessary ports if required by your application

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Use Node.js version 20

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: |
          docker run -it -v $PWD:/e2e -w /e2e --network=host cypress/included:8.5.0 run --spec 'cypress/integration/*.spec.js'
